### PR TITLE
Move #nowarn "40" compiler directive at the bottom,

### PR DESCRIPTION
**Pull request by moodmosaic**
similar to 8714eb0 ("Move Jack.Tests.MinimalTests.genExp at the bottom,", 2016-10-22) in #36.

### CODE REVIEW

**Comment by moodmosaic** [comment]
I see 1 failing check on CI, but it's probably a false negative as it goes fine on my local:

```
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Jack.Tests
  Discovered:  Jack.Tests
  Starting:    Jack.Tests
  Finished:    Jack.Tests
=== TEST EXECUTION SUMMARY ===
   Jack.Tests  Total: 50, Errors: 0, Failed: 0, Skipped: 0, Time: 43.307s
Finished Target: Test

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Build      00:00:05.0106771
Test       00:00:44.4240425
Total:     00:00:49.4652918
Status:    Ok
---------------------------------------------------------------------
```

**Comment by jystic** [comment]
I just kicked off another build

**Comment by moodmosaic** [comment]
Build is now green 🎉

**Comment by jystic** [comment]
woohoo 🍏

**Pull request merged**
