### PR TITLE
Add Jack.UnitTests project

### PR DESCRIPTION
**Pull request by moodmosaic**
In order to do this, I had to move `src/*` and `Jack.fsproj` to a new `Jack` dir, and then create a unit-test project inside a new `Jack.UnitTests` dir, so that the structure looks a bit more idiomatic:

```
<DIR>  Jack
<DIR>  Jack.UnitTests
       Jack.sln
```

---

If you're fine with this layout, then the next steps would be to add/reference [xUnit.net](https://xunit.github.io/) and [Unquote](https://github.com/swensensoftware/unquote), and then add a build step in the `build.fsx` script so that it runs any tests we add later on.

### CODE REVIEW

**Comment by jystic** [comment]
I'm mostly good with this, would prefer to rename `Jack.UnitTests` -> `Jack.Tests` as I have an aesthetic thing about namespaces being single words where possible.

Also I would prefer to keep unix line endings in the repo if that's cool, I think you can set git up to do that for you with `git config core.autocrlf true`.

I'll merge this and make my fixups, I think I'll add a travis build too.

**Comment by moodmosaic** [comment]
Sounds good. I think I'm missing that config so I'll setup git that way.

**Comment by moodmosaic** [comment]
>I think you can set git up to do that for you with `git config core.autocrlf true`.

Hmm... I did that and still getting this after running `validate.sh`:

```
Nikos@Nikos-PC MINGW64 ~/Development/Projects/dotnet-jack (master)
$ ./validate.sh
Found windows line endings:
./.gitignore
./.travis.yml
./.vs/Jack/v14/.suo
./build.cmd
./build.fsx
./build.sh
./Jack/AssemblyInfo.fs
./Jack/Gen.fs
./Jack/Jack.fsproj
./Jack/paket.references
./Jack/Property.fs
./Jack/Random.fs
./Jack/Script.fsx
./Jack/Seed.fs
./Jack/Shrink.fs
./Jack/Tree.fs
./Jack.sln
./Jack.Tests/AssemblyInfo.fs
./Jack.Tests/Jack.Tests.fsproj
./Jack.Tests/Library1.fs
./Jack.Tests/paket.references
./Jack.Tests/Script.fsx
./LICENSE
./paket.dependencies
./paket.lock
./README.md
./validate.sh
```

**Comment by jystic** [comment]
Ah, that makes sense actually, the way `core.autocrlf` works you will have `\r\n` when you check out files locally, but when you commit them it converts endings to `\n` in the repo. So `./validate.sh` will only pass on unix systems. Your recent PR was just fine, so I think it is working.

**Comment by moodmosaic** [comment]
Great!

**Pull request merged**
