### PR TITLE
Add For, Combine, Delay, and Zero in gen, in order to support for-loops

### PR DESCRIPTION
**Pull request by moodmosaic**

### CODE REVIEW

**Comment by moodmosaic** [comment]
Hmm... 1 failing check. Probably a false negative? It's passing on my machine at least 😕 

```
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Jack.Tests
  Discovered:  Jack.Tests
  Starting:    Jack.Tests
  Finished:    Jack.Tests
=== TEST EXECUTION SUMMARY ===
   Jack.Tests  Total: 49, Errors: 0, Failed: 0, Skipped: 0, Time: 51.882s
Finished Target: Test

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Build      00:00:06.0854490
Test       00:00:53.5677887
Total:     00:00:59.6862144
Status:    Ok
---------------------------------------------------------------------
```

**Comment by jystic** [comment]
>    Jack.Tests  Total: 49, Errors: 0, Failed: 0, Skipped: 0, Time: 51.882s

`Failed: 0`, hmm, how annoying, will kick it again

**Comment by jystic** [comment]
This is more or less the same as the implementations from `Property` yeah? Good idea adding them here too.

**Comment by moodmosaic** [comment]
Yep, it's more or less the same as the implementations from `Property`. The build now succeeds 🎉

**Comment by jystic** [comment]
Nice, this is good to have :1st_place_medal:

**Pull request merged**
