### PR TITLE
Make functions in Seed module private,

### PR DESCRIPTION
**Pull request by moodmosaic**
if they aren't used outside of the module.

---

Basically, I came across this while working on #26 (for which I _do_ have something locally that seems to work, _yay!_) 😃

### CODE REVIEW

**Comment by jystic** [comment]
I'm not so sure about this, it seems perfectly reasonable that someone might want to use these lower level functions? what's your motivation? just API compatibility?

> for which I do have something locally that seems to work, yay!

Awesome!

**Comment by moodmosaic** [comment]
>it seems perfectly reasonable that someone might want to use these lower level functions?

The more we expose, the more we'd have to maintain.

If these functions aren't used outside of the `Seed` module perhaps we could just make them private. After all, the interface of a Seed is

* the function that returns a new Seed
* one or more *nextXyz* functions that generate numbers
* the split function that returns a new, different, Seed

The rest are just implementation details in most cases...

**Comment by moodmosaic** [comment]
After we reach `v1`, it'll be a breaking change, according to [SemVer](http://semver.org/), if we change (API) functions from public to private. But, right now, these proposed change could be considered 'safe'. 😉

**Comment by moodmosaic** [comment]
Closing this because of #44. We can reopen it in the future, if necessary.

**Pull request closed without merging**
